#!/bin/bash

echo "=== Maven Test Diagnostics ==="
echo "Current directory: $(pwd)"
echo "Java version:"
java -version 2>&1 || echo "Java not found"
echo ""
echo "Maven version:"
mvn --version 2>&1 || echo "Maven not found"
echo ""
echo "Project structure:"
ls -la
echo ""
echo "POM file exists:"
ls -la pom.xml 2>/dev/null && echo "Yes" || echo "No"
echo ""
echo "Target directory:"
ls -la target/ 2>/dev/null || echo "No target directory"
echo ""
echo "Test classes:"
find src/test -name "*.java" 2>/dev/null | wc -l || echo "No test files found"
echo ""
echo "Running Maven compile..."
mvn compile -q 2>&1 && echo "Compile successful" || echo "Compile failed"
echo ""
echo "Running Maven test..."
mvn test -q -Dtest=LoginTest 2>&1 && echo "Test successful" || echo "Test failed"
